<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <LightningDBTargetRuntimeRelativePath>.\</LightningDBTargetRuntimeRelativePath>
    <Configurations>DebugLinuxArm32;DebugLinuxArm64;DebugLinuxX64;DebugMacOSX64;DebugMacOSArm64;DebugWindowsX64;DebugWindowsArm64</Configurations>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\LightningDB\LightningDB.csproj" />
    </ItemGroup>

    <Import Project="..\LightningDB\LightningDB.targets" />

</Project>
